---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../preferences

patches:
  - target:
      kind: VirtualMachinePreference
    patch: |-
      apiVersion: instancetype.kubevirt.io/v1beta1
      metadata:
        name: VirtualMachinePreference
      kind: VirtualMachinePreference
      $patch: delete
