---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  name: requirements
spec:
  # https://wiki.alpinelinux.org/wiki/Requirements
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 512Mi
