---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachineClusterPreference
metadata:
  name: requirements
spec:
  # https://ubuntu.com/server/docs/installation
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 2Gi
