apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Take U as it is, and modify it
resources:
  - ../u

replacements:
  - source:
      kind: VirtualMachineInstancetype
      name: u1.medium
      fieldPath: metadata.annotations.[series.nv]
    targets:
      - select:
          kind: VirtualMachineInstancetype
        fieldPaths:
          - metadata.name
        options:
          delimiter: "."
          index: 0

patches:
  - path: uo1.yaml
    target:
      name: ".*"
