# https://aws.amazon.com/ec2/instance-types/#Accelerated_Computing
apiVersion: instancetype.kubevirt.io/v1alpha2
kind: VirtualMachineInstancetype
metadata:
  name: "gn1"
  annotations:
    series.name: "gn"
    series.name_expanded: "GPU NVIDIA"
    series.nv: "gn1"
    series.description: |-
      The GN Series provides instances types intended for VMs with
      NVIDIA GPU resources attached.

      *GN* is the abbreviation of "GPU NVIDIA".

      This series is intended to be used with VMs consuming GPUs
      provided by the [NVIDIA GPU Operator](https://github.com/NVIDIA/gpu-operator)
      which is made available on OpenShift via OperatorHub.
    series.class: "GPU"
    series.icon.fas: fa-microchip
spec:
  gpus:
  - deviceName: "gpu0"
    name: "nvidia.com/A400"
