---
apiVersion: instancetype.kubevirt.io/v1beta1
kind: VirtualMachinePreference
metadata:
  name: requirements
spec:
  # https://www.microsoft.com/en-gb/windows/windows-11-specifications?r=1
  requirements:
    cpu:
      guest: 1
    memory:
      guest: 4Gi
